---
- hosts: all
  become: true
  tasks:
    - name: Ensure chrony (for time synchronization) is installed.
      yum:
        name: chrony
        state: present
        use_backend: yum

    - name: Ensure chrony is running
      service:
        name: chronyd
        state: started
        enabled: yes
