---
- hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest

    - name: Ensure apache2 is running
      service:
        name: apache2
        state: started
        enabled: true
